In [39]:
import altair as alt
import pandas as pd

alt.data_transformers.disable_max_rows()

df = pd.read_csv('https://github.com/UIUC-iSchool-DataViz/is445_data/raw/main/licenses_fall2022.csv')
df

,_id,License Type,Description,License Number,License Status,Business,Title,First Name,Middle,Last Name,...,Specialty/Qualifier,Controlled Substance Schedule,Delegated Controlled Substance Schedule,Ever Disciplined,LastModifiedDate,Case Number,Action,Discipline Start Date,Discipline End Date,Discipline Reason
0,1189509,DETECTIVE BOARD,PERMANENT EMPLOYEE REGISTRATION,129446286,NOT RENEWED,N,NaN,EILEEN,NaN,SANTACRUZ,...,NaN,NaN,NaN,N,03/18/2022,NaN,NaN,NaN,NaN,NaN
1,801037,DETECTIVE BOARD,FIREARM CONTROL CARD,229030294.0,NOT RENEWED,N,NaN,DAGMAR,J,NORDLUND,...,NaN,NaN,NaN,N,08/16/2006,NaN,NaN,NaN,NaN,NaN
2,365129,COSMO,LICENSED COSMETOLOGIST,11053076.0,NOT RENEWED,N,NaN,RADOJE,NaN,ZELENOVIC,...,NaN,NaN,NaN,N,05/26/2006,NaN,NaN,NaN,NaN,NaN
3,595427,COSMO,LICENSED COSMETOLOGIST,11295645.0,ACTIVE,N,NaN,BECKY SUE,L,BURROUGHS,...,NaN,NaN,NaN,N,11/12/2021,NaN,NaN,NaN,NaN,NaN
4,653668,COSMO,LICENSED NAIL TECHNICIAN,169006247,NOT RENEWED,N,NaN,BILL G,L,LETNER,...,NaN,NaN,NaN,N,05/30/2006,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,888281,DETECTIVE BOARD,PERMANENT EMPLOYEE REGISTRATION,129002843.0,NOT RENEWED,N,NaN,JENNIFER,NaN,DARROW,...,NaN,NaN,NaN,N,08/03/2006,NaN,NaN,NaN,NaN,NaN
9996,766623,DETECTIVE BOARD,FIREARM CONTROL CARD,229014180,TERMINATED CARD RETURNED,N,NaN,BRYAN,NaN,WILLIAMS,...,NaN,NaN,NaN,N,08/07/2006,NaN,NaN,NaN,NaN,NaN
9997,399398,COSMO,LICENSED COSMETOLOGIST,11120249,NOT RENEWED,N,NaN,EUGENE,NaN,HENDERSON JR,...,NaN,NaN,NaN,N,05/26/2006,NaN,NaN,NaN,NaN,NaN
9998,486713,COSMO,LICENSED COSMETOLOGIST,11193270,ACTIVE,N,NaN,MAHLON DOUGLAS,NaN,CLIFT,...,NaN,NaN,NaN,N,12/17/2021,NaN,NaN,NaN,NaN,NaN
9999,744770,DENTAL,REGISTERED DENTAL HYGIENIST,020012709,ACTIVE,N,NaN,KAREEM,L,HARRIS,...,NaN,NaN,NaN,N,10/25/2021,NaN,NaN,NaN,NaN,NaN

In [40]:
df.isna().sum()

_id                                            0
License Type                                   0
Description                                    0
License Number                                60
License Status                                 0
Business                                       0
Title                                       9890
First Name                                   395
Middle                                      6378
Last Name                                    395
Prefix                                      9997
Suffix                                      9590
Business Name                                  0
BusinessDBA                                 9885
Original Issue Date                            5
Effective Date                               792
Expiration Date                              500
City                                          11
State                                          0
Zip                                           71
County                                       411
Specialty/Qualifier                         9692
Controlled Substance Schedule               9791
Delegated Controlled Substance Schedule    10000
Ever Disciplined                               0
LastModifiedDate                               0
Case Number                                 9657
Action                                      9658
Discipline Start Date                       9657
Discipline End Date                         9861
Discipline Reason                           9713
dtype: int64

In [41]:
licenses = df[['License Type', 'License Status', 'County']].dropna()
licenses

         License Type            License Status   County
0     DETECTIVE BOARD               NOT RENEWED     COOK
1     DETECTIVE BOARD               NOT RENEWED     KANE
2               COSMO               NOT RENEWED     COOK
3               COSMO                    ACTIVE   DUPAGE
4               COSMO               NOT RENEWED     COOK
...               ...                       ...      ...
9995  DETECTIVE BOARD               NOT RENEWED     WILL
9996  DETECTIVE BOARD  TERMINATED CARD RETURNED     COOK
9997            COSMO               NOT RENEWED     COOK
9998            COSMO                    ACTIVE     COOK
9999           DENTAL                    ACTIVE  MCHENRY

[9589 rows x 3 columns]

In [42]:
license_type = licenses['License Type'].value_counts().reset_index()
license_type.columns = ['License Type', 'Count']
license_type

              License Type  Count
0          DETECTIVE BOARD   4759
1                    COSMO   3579
2                   DENTAL    681
3     FUNERAL AND EMBALMER     97
4   DIETETIC AND NUTRITION     69
5              DESIGN FIRM     66
6     MASSAGE LICENSING BD     50
7           HOME INSPECTOR     42
8           COMM ASSOC MGR     37
9        CLIN PSYCHOLOGIST     24
10         INTERIOR DESIGN     21
11               ARCHITECT     19
12     LAND SURVEYOR BOARD     17
13       COLLECTION AGENCY     16
14    LIMITED LIABILITY CO     16
15   HME AND SERVICES PROV     15
16   MAR AND FAM THERAPIST     14
17        ATHLETIC TRAINER     14
18     ENVIRON. HLTH PRACT     10
19               ATHLETICS      9
20                    IDPR      8
21                 GEOLOGY      7
22     LANDSCAPE ARCHITECT      7
23               APPRAISAL      4
24           MEDICAL BOARD      4
25              AUCTIONEER      2
26      CEMETERY OVERSIGHT      1
27       DETECT. DECEPTION      1

In [43]:
plot1 = alt.Chart(license_type).mark_bar().encode(
    x = alt.X('Count:Q', title = 'Num of Licenses'),
y = alt.Y('License Type:N', sort = '-x', title = 'License Type'),
color = alt.value('steelblue'),
tooltip = ['License Type', 'Count'],
).properties(width = 600, height = 400, title='Num of Licenses by License Types')
plot1

/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.Chart(...)

In [44]:
plot1.save('license_types.json')
plot1.save('license_types.html')

/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

In [45]:
# I used ChatGPT 5.4 to help me with printing the county names correctly. Initially, no values were printing out because I didn't include .index so it was returning nothing.
county = licenses.dropna(subset = ['County'])
status = county.groupby(['County', 'License Status']).size().reset_index(name = 'Count')
top_10 = county['County'].value_counts().head(10).index
status = status[status['County'].isin(top_10)]
status

        County            License Status  Count
58        COOK                    ACTIVE   1122
59        COOK                 CANCELLED     25
60        COOK       CHANGE OF OWNERSHIP      4
61        COOK                    CLOSED      8
62        COOK                  DECEASED     27
..         ...                       ...    ...
471  WINNEBAGO                  INACTIVE      9
472  WINNEBAGO               INOPERATIVE      1
473  WINNEBAGO               NOT RENEWED    114
474  WINNEBAGO  TERMINATED CARD RETURNED      5
475  WINNEBAGO   TERMINATED VALID REASON      1

[85 rows x 3 columns]

In [49]:
dropdown =  alt.binding_select(
    options = list(status['License Status']), name = 'License Status: ')
select = alt.param( bind = dropdown, value = status['License Status'])

plot2 = alt.Chart(status).add_params(select).transform_filter(alt.datum['License Status'] == select).mark_bar().encode(
    x = alt.X('Count:Q', title = 'Num of Licenses'), y = alt.Y('County:N', sort = '-x', title = 'County'),
    color = alt.value('steelblue'),
    tooltip = ['County', 'License Status', 'County']).properties(
    width = 600, height = 400, title = 'Top Counties Listed by License Status')
plot2

/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.Chart(...)

In [47]:
plot2.save('status.json')
plot2.save('status.html')

/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)